language: php

php:
   - 5.5
   - 5.6
   - 7.0

matrix:
    allow_failures:
        - php: 7.0

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - mysql -e "CREATE USER 'user'@'localhost';" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'user'@'localhost' WITH GRANT OPTION;" -uroot
    - mysql -e "FLUSH PRIVILEGES;" -uroot
    - mysql -e "CREATE DATABASE IF NOT EXISTS wasp;" -uroot

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
    - rm -rf src/Application/Cache/AppCache.php
    - php vendor/bin/coveralls -v
