services:
    connection:
        class: Wasp\Database\Connection
        arguments: ["@connections"]
    connections:
        class: Wasp\Database\ConnectionCollection
        calls:
            - [setDI, ["@service_container"]]
    connection_validator:
        class: Wasp\Database\ConnectionValidator
        scope: prototype
    fs:
        class: Symfony\Component\Filesystem\Filesystem
