services:
    connection:
        class: Wasp\Database\Connection
        arguments: ["@connections"]
    connections:
        class: Wasp\Database\ConnectionCollection
        tags:
            - { name: container.injectable }
    connection_validator:
        class: Wasp\Database\ConnectionValidator
        scope: prototype
    fs:
        class: Symfony\Component\Filesystem\Filesystem
