services:
    connection:
        class: Wasp\Database\Connection
        arguments: 
            - "@connections"
    connections:
        class: Wasp\Database\ConnectionCollection
        calls:
            - [setDI, ["@service_container"]]
    connection_validator:
        class: Wasp\Database\ConnectionValidator
        scope: prototype
    database:
        class: Wasp\Database\Database
        arguments:
            - "@connection"
    schema:
        class: Wasp\Database\Schema
        lazy: true
        arguments:
            - "@connection"
    fs:
        class: Symfony\Component\Filesystem\Filesystem
        lazy: true
