services:
    connection:
        class: Wasp\Database\Connection
        arguments: ["@connections"]
    connections:
        class: Wasp\Database\ConnectionCollection
    fs:
        class: Symfony\Component\Filesystem\Filesystem
