services:
    connection:
        class: Wasp\Database\Connection
        arguments: 
            - "@connections"
    connections:
        class: Wasp\Database\ConnectionCollection
        calls:
            - [setDI, ["@service_container"]]
    connection_validator:
        class: Wasp\Database\ConnectionValidator
        scope: prototype
    console:
        class: Wasp\Console\ConsoleApplication
        lazy: true
        calls:
            - [setDI, ["@service_container"]]
    config:
        class: Danzabar\Config\Files\ConfigFile
        lazy: true
        scope: prototype
    commandloader:
        class: Wasp\Console\CommandLoader
        lazy: true
        arguments:
            - "@console"
    event_dispatch:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        lazy: true
        arguments:
            - "@service_container"
    event_register:
        class: Wasp\Events\EventRegister
        lazy: true
        arguments:
            - "@event_dispatch"
    database:
        class: Wasp\Database\Database
        arguments:
            - "@connection"
    dispatcher:
        class: Wasp\Controller\Dispatcher
        calls:
            - [setDI, ["@service_container"]]
    diawaretwig:
        class: Wasp\Templating\DIAwareTwigContainer
        lazy: true
        arguments:
            - "@service_container"
    finder:
        class: Symfony\Component\Finder\Finder
        lazy: true
        scope: prototype
    filter:
        class: Wasp\Filters\Filter
        lazy: true
        calls:
            - [setDI, ["@service_container"]]
    fixtures:
        class: Wasp\Database\FixtureManager
        lazy: true
        arguments:
            - "@connection"
    fs:
        class: Symfony\Component\Filesystem\Filesystem
        lazy: true
    jsonresponse_api:
        class: Symfony\Component\HttpFoundation\JsonResponse
        lazy: true
        scope: prototype
    module.builder:
        class: Wasp\Modules\ModuleBuilder
        lazy: true
        calls:
            - [setDI, ["@service_container"]]
    module.manager:
        class: Wasp\Modules\ModuleManager
        lazy: true
        arguments: ["@module.cache", "@module.builder"]
    module.cache:
        class: Wasp\Modules\ModuleCache
        lazy: true
        calls:
            - [setDI, ["@service_container"]]
    response_api:
        class: Symfony\Component\HttpFoundation\Response
        lazy: true
        scope: prototype
    response:
        class: Wasp\Controller\Response
        lazy: true
        calls:
           - [setDI, ["@service_container"]]
    request:
        class: Wasp\Routing\Request
        lazy: true
        arguments: 
            - "@session"
    route_collection:
        class: Symfony\Component\Routing\RouteCollection
    route:
        class: Wasp\Routing\Route
        arguments:
            - "@route_collection"
    router:
        class: Wasp\Routing\Router
        calls:
            - [setDI, ["@service_container"]]
    schema:
        class: Wasp\Database\Schema
        lazy: true
        arguments:
            - "@connection"
    session:
        class: Symfony\Component\HttpFoundation\Session\Session
        lazy: true
    serializer:
        class: Wasp\Utils\Serializer
        lazy: true
    phpengine:
        class: Wasp\Templating\Engines\PHPEngine
        lazy: true
        arguments:
            - "@template"
    profile:
        class: Wasp\Application\Profile
        arguments:
            - "@fs"
    template:
        class: Wasp\Templating\Template
        lazy: true
    twigengine:
        class: Wasp\Templating\Engines\TwigEngine
        lazy: true
        arguments:
            - "@template"
            - "@fs"
            - "@diawaretwig"
    url:
        class: Wasp\Routing\URL
        lazy: true
        arguments:
            - "@request"
            - "@route_collection"
