services:
    connection:
        class: Wasp\Database\Connection
        arguments: 
            - "@connections"
    connections:
        class: Wasp\Database\ConnectionCollection
        calls:
            - [setDI, ["@service_container"]]
    connection_validator:
        class: Wasp\Database\ConnectionValidator
        scope: prototype
    database:
        class: Wasp\Database\Database
        arguments:
            - "@connection"
    dispatcher:
        class: Wasp\Controller\Dispatcher
        calls:
            - [setDI, ["@service_container"]]
    fixtures:
        class: Wasp\Database\FixtureManager
        lazy: true
        arguments:
            - "@connection"
    fs:
        class: Symfony\Component\Filesystem\Filesystem
        lazy: true
    response_api:
        class: Symfony\Component\HttpFoundation\Response
        lazy: true
        scope: prototype
    response:
        class: Wasp\Controller\Response
        lazy: true
        calls:
           - [setDI, ["@service_container"]]
    request:
        class: Wasp\Routing\Request
        lazy: true
    schema:
        class: Wasp\Database\Schema
        lazy: true
        arguments:
            - "@connection"

