services:
    connection:
        class: Wasp\Database\Connection
        arguments: 
            - "@connections"
    connections:
        class: Wasp\Database\ConnectionCollection
        calls:
            - [setDI, ["@service_container"]]
    connection_validator:
        class: Wasp\Database\ConnectionValidator
        scope: prototype
    database:
        class: Wasp\Database\Database
        arguments:
            - "@connection"
    dispatcher:
        class: Wasp\Controller\Dispatcher
        calls:
            - [setDI, ["@service_container"]]
    fixtures:
        class: Wasp\Database\FixtureManager
        lazy: true
        arguments:
            - "@connection"
    fs:
        class: Symfony\Component\Filesystem\Filesystem
        lazy: true
    jsonresponse_api:
        class: Symfony\Component\HttpFoundation\JsonResponse
        lazy: true
        scope: prototype
    response_api:
        class: Symfony\Component\HttpFoundation\Response
        lazy: true
        scope: prototype
    response:
        class: Wasp\Controller\Response
        lazy: true
        calls:
           - [setDI, ["@service_container"]]
    request:
        class: Wasp\Routing\Request
        lazy: true
    route_collection:
        class: Symfony\Component\Routing\RouteCollection
    route:
        class: Wasp\Routing\Route
        calls:
            - [setDI, ["@service_container"]]
    schema:
        class: Wasp\Database\Schema
        lazy: true
        arguments:
            - "@connection"
    session:
        class: Symfony\Component\HttpFoundation\Session\Session
        lazy: true
    phpengine:
        class: Wasp\Templating\Engines\PHPEngine
        calls:
            - [setDI, ["@service_container"]]
    template:
        class: Wasp\Templating\Template
        lazy: true
        calls:
            - [setDI, ["@service_container"]]
    twigengine:
        class: Wasp\Templating\Engines\TwigEngine
        calls:
            - [setDI, ["@service_container"]]
    url:
        class: Wasp\Routing\URL
        lazy: true
        calls:
            - [setDI, ["@service_container"]]
